version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-saeb
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - SERVICES=s3,dynamodb,sqs,lambda,apigateway,cloudwatch,iam
      - DEBUG=1
      - PERSISTENCE=1
      - S3_SKIP_SIGNATURE_VALIDATION=1
    volumes:
      - "./localstack/init:/etc/localstack/init"
      - "./localstack/data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
