AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  GenerateReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.handler
      Runtime: python3.12
      Timeout: 30
      Environment:
        Variables:
          S3_OUTPUT_BUCKET_NAME: saeb-student-report
          DYNAMO_REPORTS_TABLE: saeb_reports_local
