AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ManageReportQuestionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.handler
      Runtime: python3.12
      Timeout: 30
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://host.docker.internal:8000
          DYNAMO_QUESTIONS_TABLE: saeb_questions
          DYNAMMO_INTERVENTIONS_TABLE: saeb_interventions
      Events:
        CreateQuestion:
          Type: Api
          Properties:
            Path: /questions/create
            Method: post
        CreateIntervention:
          Type: Api
          Properties:
            Path: /interventions/create
            Method: post
