AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ManageReportQuestionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.handler
      Runtime: python3.12
      Timeout: 30
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://host.docker.internal:4566
          DYNAMO_QUESTIONS_TABLE: saeb_questions_local
          DYNAMO_INTERVENTIONS_TABLE: saeb_interventions_local
      Events:
        GetQuestions:
          Type: HttpApi
          Properties:
            Path: /questions/all
            Method: get
            RequestParameters:
              - method.request.querystring.limit:
                  Required: false
                  Caching: false
              - method.request.querystring.next_token:
                  Required: false
                  Caching: false
        CreateQuestion:
          Type: HttpApi
          Properties:
            Path: /questions/create
            Method: post
        GetInterventions:
          Type: HttpApi
          Properties:
            Path: /interventions/all
            Method: get
            RequestParameters:
              - method.request.querystring.limit:
                  Required: false
                  Caching: false
              - method.request.querystring.next_token:
                  Required: false
                  Caching: false
        CreateIntervention:
          Type: HttpApi
          Properties:
            Path: /interventions/create
            Method: post
