name: Deploy Lambda

on:
  push:
    branches:
      - prd
      - stg
      - dev

env:
  AWS_REGION: sa-east-1
  S3_BUCKET: saeb-lambda-artifacts
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # LAMBDA MANAGE REPORT QUESTIONS
  MANAGE_REPORT_QUESTIONS_LAMBDA: manage-report-questions
  MANAGE_REPORT_QUESTIONS_LAMBDA_ZIP: manage-report-questions-${{ github.sha }}.zip

  # LAMBDA GENERATE PRESIGNED URL
  GENERATE_PRESIGNED_URL_LAMBDA: generate-presigned-url
  GENERATE_PRESIGNED_URL_LAMBDA_ZIP: generate-presigned-url-${{ github.sha }}.zip

jobs:
  deploy:
    environment: ${{ github.ref == 'refs/heads/prd' && 'prd' || github.ref == 'refs/heads/dev' && 'dev' || github.ref == 'refs/heads/stg' && 'stg' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # DEPLOY MANAGE REPORT QUESTIONS LAMBDA
      - name: SAM build
        run: |
          cd src/functions/manage-report-questions
          sam build

      - name: Zip lambda
        run: |
          cd src/functions/manage-report-questions/.aws-sam/build/ManageReportQuestionsFunction
          zip -r ../../../${MANAGE_REPORT_QUESTIONS_LAMBDA_ZIP} .

      - name: Upload artifact to S3
        run: |
          aws s3 cp src/functions/manage-report-questions/${MANAGE_REPORT_QUESTIONS_LAMBDA_ZIP} s3://${S3_BUCKET}/${MANAGE_REPORT_QUESTIONS_LAMBDA_ZIP}

      - name: Deploy lambda
        run: |
          aws lambda update-function-code \
            --function-name ${MANAGE_REPORT_QUESTIONS_LAMBDA} \
            --s3-bucket ${S3_BUCKET} \
            --s3-key ${MANAGE_REPORT_QUESTIONS_LAMBDA_ZIP}

      - name: Wait for update
        run: |
          aws lambda wait function-updated \
            --function-name ${MANAGE_REPORT_QUESTIONS_LAMBDA}

      # DEPLOY GENERATE PRESIGNED URL LAMBDA
      - name: SAM build
        run: |
          cd src/functions/generate-presigned-url
          sam build

      - name: Zip lambda
        run: |
          cd src/functions/generate-presigned-url/.aws-sam/build/GeneratePresignedUrlFunction
          zip -r ../../../${GENERATE_PRESIGNED_URL_LAMBDA_ZIP} .

      - name: Upload artifact to S3
        run: |
          aws s3 cp src/functions/generate-presigned-url/${GENERATE_PRESIGNED_URL_LAMBDA_ZIP} s3://${S3_BUCKET}/${GENERATE_PRESIGNED_URL_LAMBDA_ZIP}

      - name: Deploy lambda
        run: |
          aws lambda update-function-code \
            --function-name ${GENERATE_PRESIGNED_URL_LAMBDA} \
            --s3-bucket ${S3_BUCKET} \
            --s3-key ${GENERATE_PRESIGNED_URL_LAMBDA_ZIP}

      - name: Wait for update
        run: |
          aws lambda wait function-updated \
            --function-name ${GENERATE_PRESIGNED_URL_LAMBDA}
